/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExportInquiryRouteImport } from './routes/export-inquiry'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as AgriculturalInquiryRouteImport } from './routes/agricultural-inquiry'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportInquiryRoute = ExportInquiryRouteImport.update({
  id: '/export-inquiry',
  path: '/export-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalInquiryRoute = AgriculturalInquiryRouteImport.update({
  id: '/agricultural-inquiry',
  path: '/agricultural-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-inquiry': typeof AgriculturalInquiryRoute
  '/crops': typeof CropsRoute
  '/export-inquiry': typeof ExportInquiryRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-inquiry': typeof AgriculturalInquiryRoute
  '/crops': typeof CropsRoute
  '/export-inquiry': typeof ExportInquiryRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agricultural-inquiry': typeof AgriculturalInquiryRoute
  '/crops': typeof CropsRoute
  '/export-inquiry': typeof ExportInquiryRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agricultural-inquiry'
    | '/crops'
    | '/export-inquiry'
    | '/insights'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agricultural-inquiry'
    | '/crops'
    | '/export-inquiry'
    | '/insights'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agricultural-inquiry'
    | '/crops'
    | '/export-inquiry'
    | '/insights'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgriculturalInquiryRoute: typeof AgriculturalInquiryRoute
  CropsRoute: typeof CropsRoute
  ExportInquiryRoute: typeof ExportInquiryRoute
  InsightsRoute: typeof InsightsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-inquiry': {
      id: '/export-inquiry'
      path: '/export-inquiry'
      fullPath: '/export-inquiry'
      preLoaderRoute: typeof ExportInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural-inquiry': {
      id: '/agricultural-inquiry'
      path: '/agricultural-inquiry'
      fullPath: '/agricultural-inquiry'
      preLoaderRoute: typeof AgriculturalInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgriculturalInquiryRoute: AgriculturalInquiryRoute,
  CropsRoute: CropsRoute,
  ExportInquiryRoute: ExportInquiryRoute,
  InsightsRoute: InsightsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
